server:
  port: ${SERVER_PORT:8001}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/auth-service}

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: auth-service
  http:
    encoding:
      charset: ${SPRING_HTTP_ENCODING_CHARSET:UTF-8}
      enabled: ${SPRING_HTTP_ENCODING_ENABLED:true}
      force: ${SPRING_HTTP_ENCODING_FORCE:true}
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/auth_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh&useUnicode=true&characterEncoding=UTF-8}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:true}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP:auth-service-group}
      auto-offset-reset: ${KAFKA_AUTO_OFFSET_RESET:earliest}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "${KAFKA_JSON_TRUSTED_PACKAGES:com.service.auth.events,com.service.profile.events}"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  task:
    scheduling:
      enabled: ${TASK_SCHEDULING_ENABLED:true}

jwt:
  signerKey: "${JWT_SIGNER_KEY}"
  valid-duration: ${JWT_VALID_DURATION:3600} # in seconds
  refreshable-duration: ${JWT_REFRESHABLE_DURATION:36000} # in seconds

app:
  services:
    profile: ${PROFILE_SERVICE_URL:http://localhost:8003/profiles}

outbox:
  publisher:
    fixedDelay: ${OUTBOX_PUBLISHER_FIXED_DELAY:1000}

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized