server:
  port: 8004
  servlet:
    context-path: /analytics
spring:
  application:
    name: analytics_service
  datasource:
    url: "jdbc:mysql://localhost:3306/analytics_db"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true